# coding:utf-8

[pytest]

asyncio_mode = auto
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
allure_show_untested = false
allure_full_name = false
allure_display_source = false  # 不显示源代码


xfail_strict = True

python_files = test_*
python_classes = Test*
python_functions = test_*

console_output_style = count

addopts = -v --alluredir allure-results --disable-warnings --color yes --no-header --cov=aiotest --cov-report=term --cov-report=html:coverage_report --cov-report=term-missing
